/**
 * Generates the machine-readable navigation surface for the docs:
 *
 * - `public/llms.txt`     — llms.txt index, one line per page carrying that
 *                           page's frontmatter description
 * - `public/sitemap.xml`  — every route, with `lastmod` from git (untracked,
 *                           regenerated by `build`; see GENERATE_ONLY below)
 * - `public/robots.txt`   — points crawlers at the sitemap
 *
 * All three come from the sidebar (the Fumadocs page tree built from
 * `meta.json` files) and page frontmatter, so the index cannot drift out of
 * sync with the sidebar the way a hand-written one does. Sections come from
 * the top-level separators; nested separators only group visually.
 *
 * Usage: `pnpm generate:ai-nav` (runs as part of `build`).
 * `--check` regenerates in memory and exits non-zero if a *tracked* output is
 * stale, or if a page is missing from the sidebar, so CI catches either.
 */
import fs from 'node:fs'
import path from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { loadSource, publicDir, root, SITE, site } from './lib/pages.js'

const run = promisify(execFile)

// ---- sidebar walk --------------------------------------------------------

/**
 * Flattens the page tree into `{ route, title, section }`, depth-first.
 * `title` is the sidebar label (`sidebarTitle`, or a folder's meta.json title).
 *
 * Each sidebar tab (root folder) is walked as its own top level. The tab that
 * holds the home page keeps its separator names as sections; the others are
 * prefixed with the tab name ("Client SDKs: Platforms").
 */
function walkNav(nodes, section, out = [], depth = 0, tab = null) {
    for (const node of nodes) {
        if (node.type === 'separator') {
            if (depth === 0 && node.name) section = tab ? `${tab}: ${node.name}` : node.name
            continue
        }
        if (node.type === 'page') {
            if (!node.external && node.$ref) out.push({ route: node.url, title: node.name, section })
            continue
        }
        if (node.root) {
            const home = node.children.some((c) => c.type === 'page' && c.url === '/')
            walkNav(node.children, home ? section : node.name, out, 0, home ? null : node.name)
            continue
        }
        // folder: its index page carries the folder's label
        if (node.index) out.push({ route: node.index.url, title: node.name, section })
        walkNav(node.children, section, out, depth + 1, tab)
    }
    return out
}

// ---- git lastmod ---------------------------------------------------------

/**
 * Commits that touched every page without changing what it says (the Fumadocs
 * move and syntax conversion). Skipped so a page's lastmod stays its last real edit.
 */
function ignoredRevs() {
    const file = path.join(root, '.git-blame-ignore-revs')
    if (!fs.existsSync(file)) return new Set()
    return new Set(fs.readFileSync(file, 'utf8').split('\n').map((l) => l.trim()).filter((l) => /^[0-9a-f]{7,40}$/.test(l)))
}

/**
 * file -> ISO date of the last commit that touched it, following renames.
 * Shallow clones only know the tip commit, which would stamp every page with
 * the same date — worse than no `lastmod` at all, so bail out.
 */
async function lastModified(files) {
    const git = (args) => run('git', args, { cwd: root, maxBuffer: 16 * 1024 * 1024 }).then((r) => r.stdout)
    const dates = new Map()
    try {
        if ((await git(['rev-parse', '--is-shallow-repository'])).trim() === 'true') return dates
    } catch {
        return dates // not a git checkout
    }
    const skip = ignoredRevs()
    const isSkipped = (sha) => [...skip].some((s) => sha.startsWith(s))
    await Promise.all(files.map(async (file) => {
        const log = await git(['log', '--follow', '--format=%H %cI', '--', file]).catch(() => '')
        const hit = log.split('\n').map((l) => l.split(' ')).find(([sha, date]) => sha && date && !isSkipped(sha))
        if (hit) dates.set(file, hit[1])
    }))
    return dates
}

// ---- renderers -----------------------------------------------------------

function renderLlms(nav, pages) {
    const home = pages.get('/')
    const lines = [`# ${site.name}`, '']
    if (home?.description) lines.push(`> ${home.description}`, '')
    lines.push(`Documentation for Colyseus ${site.version}.`, '')

    // Without this the markdown twins exist but nothing points at them.
    lines.push(
        `Every page is also available as raw markdown: append \`.md\` to any URL, e.g. ${SITE}/room.md.`,
        `The full corpus is at ${SITE}/llms-full.txt.`,
        '',
    )

    let section = null
    for (const item of nav) {
        if (item.section !== section) {
            section = item.section
            if (lines.at(-1) !== '') lines.push('')
            lines.push(`## ${section}`, '')
        }
        // The home page's description is already the `>` blurb above.
        const description = item.route === '/' ? '' : pages.get(item.route).description
        const url = item.route === '/' ? `${SITE}/` : SITE + item.route
        lines.push(`- [${item.title}](${url})${description ? `: ${description}` : ''}`)
    }
    return lines.join('\n').trimEnd() + '\n'
}

const xmlEscape = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

async function renderSitemap(nav, pages) {
    const routes = [...new Set(nav.map((i) => i.route))].sort()
    const dates = await lastModified(routes.map((r) => pages.get(r).file))
    const urls = routes.map((route) => {
        const lastmod = dates.get(pages.get(route).file)
        return [
            '  <url>',
            `    <loc>${xmlEscape(route === '/' ? `${SITE}/` : SITE + route)}</loc>`,
            ...(lastmod ? [`    <lastmod>${lastmod.slice(0, 10)}</lastmod>`] : []),
            '  </url>',
        ].join('\n')
    })
    return [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        ...urls,
        '</urlset>',
        '',
    ].join('\n')
}

const renderRobots = () => `User-agent: *\nAllow: /\n\nSitemap: ${SITE}/sitemap.xml\n`

// ---- main ----------------------------------------------------------------

const check = process.argv.includes('--check')
const { source, pages } = loadSource()
const nav = walkNav(source.pageTree.children, 'Overview')

const covered = new Set(nav.map((i) => i.route))
const orphans = [...pages.keys()].filter((r) => !covered.has(r))
const undescribed = nav.filter((i) => !pages.get(i.route).description)

const outputs = {
    'llms.txt': renderLlms(nav, pages),
    'sitemap.xml': check ? null : await renderSitemap(nav, pages),
    'robots.txt': renderRobots(),
}

/**
 * Written, never gated. `sitemap.xml` stamps each route with the date of the
 * commit that last touched its page, which a pre-commit hook cannot know: the
 * commit being made is not in `git log` yet, so the sitemap the hook approves
 * is stale the instant that commit lands, and the *next* commit gets blamed.
 * It is gitignored and regenerated by `build`, where history is settled.
 */
const GENERATE_ONLY = new Set(['sitemap.xml'])

const stale = []
for (const [name, content] of Object.entries(outputs)) {
    if (check && GENERATE_ONLY.has(name)) continue
    const file = path.join(publicDir, name)
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null
    if (current === content) continue
    if (check) stale.push(name)
    else fs.writeFileSync(file, content)
}

for (const item of undescribed) console.warn(`! ${item.route} has no frontmatter description`)
for (const route of orphans) console.warn(`! ${route} is not in the sidebar: list it in its folder's meta.json`)

if (check && (stale.length || orphans.length)) {
    if (stale.length) console.log(`\n✗ stale: ${stale.join(', ')} — run \`pnpm generate:ai-nav\` and commit the result`)
    if (orphans.length) console.log(`\n✗ ${orphans.length} page(s) missing from the sidebar`)
    process.exit(1)
}

const reported = Object.keys(outputs).filter((name) => !(check && GENERATE_ONLY.has(name)))
console.log(`✓ ${check ? 'up to date' : 'generated'}: ${reported.join(', ')} (${nav.length} pages)`)
